name: instacare_components
description: Instacare UI component library
version: 1.1.0
environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.16.0"
dependencies:
  flutter:
    sdk: flutter
  country_flags: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  plugin:
    platforms:
      android:
        package: com.example.instacare_components
        pluginClass: InstacareComponentsPlugin
      ios:
        pluginClass: InstacareComponentsPlugin
      macos:
        pluginClass: InstacareComponentsPlugin
